server:
  port: 8002
#配置
spring:
  application:
    name: microservice-product  # 应用名称，会在Eureka中显示
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver   #  mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123root
    dbcp2:
      min-idle: 5 #  数据库连接池的最小维持连接数
      initial-size: 5 #  初始化连接数
      max-total: 5  #  最大连接数
      max-wait-millis: 150  #  等待连接获取的最大超时时间
#配置mybatis
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #  mybatis配置文件所在路径
  mapper-locations: classpath:mapper/*.xml #  mapper映射文件
#配置eureka 将服务提供者注册到Eureka
eureka:
  client:
    register-with-eureka: true  #  服务注册开关
    fetch-registry: true  #  服务发现开关
    serviceUrl:
#      defaultZone: http://localhost:6001/eureka
       defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
      instanceId: ${spring.application.name}:${server.port}  #  指定实例ID,就不会显示主机名了
      prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
#     ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
      lease-expiration-duration-in-seconds: 10 # 10秒即过期 服务时效时间 默认90s
      lease-renewal-interval-in-seconds: 5 # 5秒一次心跳 服务续约(renew)的间隔,默认30s


